name: Prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [development]
jobs:
  eslint:
    name: Run prettier scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prettier
        run: yarn format
        continue-on-error: true

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "Automated changes- Prettier"
          git push
